//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CRMSTUBSOFT
{
    using System;
    using System.Collections.Generic;
    
    public partial class ContratClient
    {
        public string NumeroContratClient { get; set; }
        public System.DateTime DateContratClient { get; set; }
        public string CodeClient { get; set; }
        public string CodeTypeContrat { get; set; }
        public string CodeArticle { get; set; }
        public bool Actif { get; set; }
        public System.DateTime DateDebut { get; set; }
        public System.DateTime DateFin { get; set; }
        public int OccuranceFacturation { get; set; }
        public decimal MontantHT { get; set; }
        public System.DateTime DatePremiereFactration { get; set; }
        public bool SuiteContrat { get; set; }
        public decimal TauxRemise { get; set; }
        public string ModeFacturation { get; set; }
        public string Observation { get; set; }
        public string NomUtilisateur { get; set; }
        public Nullable<System.DateTime> DateCreation { get; set; }
        public Nullable<System.DateTime> HeureCreation { get; set; }
        public System.DateTime DateFinProlongation { get; set; }
    }
}
