//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CRMSTUBSOFT
{
    using System;
    using System.Collections.Generic;
    
    public partial class Crm_Intervention
    {
        public string NumeroIntervention { get; set; }
        public System.DateTime DateInterventionDebut { get; set; }
        public System.DateTime DateInterventionFin { get; set; }
        public System.DateTime DateIntervention { get; set; }
        public System.DateTime DateCreation { get; set; }
        public string Createur { get; set; }
        public string CodeClient { get; set; }
        public string RaisonSociale { get; set; }
        public string Duree { get; set; }
        public bool Visite { get; set; }
        public bool Local { get; set; }
        public string CodeVoiture { get; set; }
        public string DescriptionIntervention { get; set; }
        public bool Voiture { get; set; }
        public string NumeroDossier { get; set; }
        public bool Paye { get; set; }
        public string Nature { get; set; }
    }
}
