//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CRMSTUBSOFT
{
    using System;
    using System.Collections.Generic;
    
    public partial class Crm_Sanction
    {
        public int IdSanction { get; set; }
        public string LibelleSanction { get; set; }
        public string NoteSanction { get; set; }
        public string TypeTache { get; set; }
        public string ModeTache { get; set; }
        public string CodeUtilisateur { get; set; }
        public Nullable<int> Degres { get; set; }
        public string TypeSanction { get; set; }
    }
}
