//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CRMSTUBSOFT
{
    using System;
    using System.Collections.Generic;
    
    public partial class Crm_Personne
    {
        public string CodePersonne { get; set; }
        public string NomPrenom { get; set; }
        public string Adresse { get; set; }
        public string Nationalite { get; set; }
        public string Tel { get; set; }
    }
}
