//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CRMSTUBSOFT
{
    using System;
    using System.Collections.Generic;
    
    public partial class Crm_Rapport
    {
        public string NumeroRapport { get; set; }
        public string DescriptionRapport { get; set; }
        public System.DateTime DateCreation { get; set; }
        public string UtilisateurCreateur { get; set; }
        public int Degres { get; set; }
        public string NumeroEtat { get; set; }
        public int NumeroOrdre { get; set; }
        public string DatePrevusProchaineReunion { get; set; }
        public Nullable<int> Duree { get; set; }
        public string Status { get; set; }
        public string CodeClient { get; set; }
        public string RaisonSociale { get; set; }
        public string NumeroDossier { get; set; }
        public System.DateTime DateRapport { get; set; }
    }
}
