//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CRMSTUBSOFT
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class CrmModelEntities : DbContext
    {
        public CrmModelEntities()
            : base("name=CrmModelEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<ContactClient> ContactClient { get; set; }
        public virtual DbSet<Crm_AccesUtilisateur> Crm_AccesUtilisateur { get; set; }
        public virtual DbSet<Crm_ContactClient> Crm_ContactClient { get; set; }
        public virtual DbSet<Crm_CycleExecTache> Crm_CycleExecTache { get; set; }
        public virtual DbSet<Crm_Intervention> Crm_Intervention { get; set; }
        public virtual DbSet<Crm_MoyenCommunication> Crm_MoyenCommunication { get; set; }
        public virtual DbSet<Crm_Notification> Crm_Notification { get; set; }
        public virtual DbSet<Crm_OperationParTicket> Crm_OperationParTicket { get; set; }
        public virtual DbSet<Crm_PersonnelParRapoort> Crm_PersonnelParRapoort { get; set; }
        public virtual DbSet<Crm_RespensableParIntervention> Crm_RespensableParIntervention { get; set; }
        public virtual DbSet<Crm_TableObjet> Crm_TableObjet { get; set; }
        public virtual DbSet<Crm_TacheExcution> Crm_TacheExcution { get; set; }
        public virtual DbSet<Crm_TacheLiee> Crm_TacheLiee { get; set; }
        public virtual DbSet<Crm_TicketClient> Crm_TicketClient { get; set; }
        public virtual DbSet<Crm_TypeOperation> Crm_TypeOperation { get; set; }
        public virtual DbSet<Crm_TypeReclamation> Crm_TypeReclamation { get; set; }
        public virtual DbSet<EtatCRM> EtatCRM { get; set; }
        public virtual DbSet<Respensable> Respensable { get; set; }
        public virtual DbSet<Utilisateur> Utilisateur { get; set; }
        public virtual DbSet<Fonction> Fonction { get; set; }
        public virtual DbSet<Service> Service { get; set; }
        public virtual DbSet<Crm_Personne> Crm_Personne { get; set; }
        public virtual DbSet<CompteurPiece> CompteurPiece { get; set; }
        public virtual DbSet<Client> Client { get; set; }
        public virtual DbSet<Crm_PersonneParReunion> Crm_PersonneParReunion { get; set; }
        public virtual DbSet<Crm_PVReunion> Crm_PVReunion { get; set; }
        public virtual DbSet<Crm_Rapport> Crm_Rapport { get; set; }
        public virtual DbSet<Crm_PersonneConcerner> Crm_PersonneConcerner { get; set; }
        public virtual DbSet<Crm_Planning> Crm_Planning { get; set; }
        public virtual DbSet<Crm_Planning_Responsable> Crm_Planning_Responsable { get; set; }
        public virtual DbSet<Crm_PlanningTime> Crm_PlanningTime { get; set; }
        public virtual DbSet<crm_ModeTache> crm_ModeTache { get; set; }
        public virtual DbSet<ContratClient> ContratClient { get; set; }
        public virtual DbSet<Crm_TacheCommercialSoft> Crm_TacheCommercialSoft { get; set; }
        public virtual DbSet<EmploiDuTemp> EmploiDuTemp { get; set; }
        public virtual DbSet<PersonnelGRH> PersonnelGRH { get; set; }
        public virtual DbSet<Crm_ClientParent> Crm_ClientParent { get; set; }
        public virtual DbSet<Crm_ClientParentAssociation> Crm_ClientParentAssociation { get; set; }
        public virtual DbSet<Crm_Equipe> Crm_Equipe { get; set; }
        public virtual DbSet<Crm_TypeTache> Crm_TypeTache { get; set; }
        public virtual DbSet<Crm_Sanction> Crm_Sanction { get; set; }
        public virtual DbSet<Crm_Degres_Sanction> Crm_Degres_Sanction { get; set; }
        public virtual DbSet<Crm_Document> Crm_Document { get; set; }
        public virtual DbSet<Crm_EquipeRespensable> Crm_EquipeRespensable { get; set; }
        public virtual DbSet<Crm_Service> Crm_Service { get; set; }
        public virtual DbSet<Crm_ServiceEquipe> Crm_ServiceEquipe { get; set; }
        public virtual DbSet<Crm_Projet> Crm_Projet { get; set; }
        public virtual DbSet<Crm_HistoriqueType> Crm_HistoriqueType { get; set; }
        public virtual DbSet<ClientCRM> ClientCRM { get; set; }
        public virtual DbSet<Crm_ModuleNature> Crm_ModuleNature { get; set; }
        public virtual DbSet<Crm_TacheNature> Crm_TacheNature { get; set; }
        public virtual DbSet<Crm_Motif> Crm_Motif { get; set; }
        public virtual DbSet<Crm_TypeProjet> Crm_TypeProjet { get; set; }
        public virtual DbSet<Crm_ChatReclamation> Crm_ChatReclamation { get; set; }
        public virtual DbSet<Crm_TacheReclamation> Crm_TacheReclamation { get; set; }
        public virtual DbSet<Crm_ReclamationClient> Crm_ReclamationClient { get; set; }
    }
}
