//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CRMSTUBSOFT
{
    using System;
    using System.Collections.Generic;
    
    public partial class Client
    {
        public string CodeClient { get; set; }
        public string Respensable { get; set; }
        public string CodeForme { get; set; }
        public string CodeFamilleClient { get; set; }
        public string CodeRepresentant { get; set; }
        public string Tel1 { get; set; }
        public string Fax1 { get; set; }
        public string Email { get; set; }
        public string SiteWeb { get; set; }
        public string RaisonSociale { get; set; }
        public string RegistreCommerce { get; set; }
        public decimal SeuilCredit { get; set; }
        public decimal SoldeCredit { get; set; }
        public decimal SeuilEngagement { get; set; }
        public decimal SoldeEngagement { get; set; }
        public bool BlocageFacturation { get; set; }
        public string Adresse1 { get; set; }
        public string CodeSousRegion { get; set; }
        public string CodeZone { get; set; }
        public string CodePostale { get; set; }
        public string CodeVille { get; set; }
        public string AresseLivraison { get; set; }
        public string CodePostaleLivraison { get; set; }
        public bool Exoneration { get; set; }
        public string NumeroExonoration { get; set; }
        public System.DateTime DateExonoration { get; set; }
        public System.DateTime DateFinExonoration { get; set; }
        public bool PayerTVA { get; set; }
        public bool Export { get; set; }
        public string NumeroExport { get; set; }
        public string CodeRemise { get; set; }
        public string MartriculeFiscale { get; set; }
        public bool TimbreFiscal { get; set; }
        public string CodeBanque { get; set; }
        public string RibBanquaire { get; set; }
        public string CodeModeReglement { get; set; }
        public decimal TauxRemise { get; set; }
        public string Observation { get; set; }
        public bool Assujetti { get; set; }
        public decimal NbJourReglement { get; set; }
        public decimal SignalReglement { get; set; }
        public bool Fodec { get; set; }
        public string CIN { get; set; }
        public string CodeComptable { get; set; }
        public bool Comptabiliser { get; set; }
        public System.DateTime DateCreation { get; set; }
        public string UtilisateurCreation { get; set; }
        public bool CalculAutoSeuilCredit { get; set; }
        public bool RemiseDepassement { get; set; }
        public bool Taxe { get; set; }
        public decimal DepassementSeuil { get; set; }
        public decimal DivCredit { get; set; }
        public bool Inactif { get; set; }
        public bool Contentieux { get; set; }
        public string ObservationGarantie { get; set; }
        public string ContactAdresseLivraison { get; set; }
        public string CodeTypeDecharge { get; set; }
        public System.DateTime DateOuvertureSociete { get; set; }
        public string NomGerant { get; set; }
        public System.DateTime DateNaissanceGerant { get; set; }
        public string Avis { get; set; }
        public string CINLivraison { get; set; }
        public string MatriculeFiscaleLivraison { get; set; }
        public System.DateTime DateOuvertureLivraison { get; set; }
        public bool ManqueDocument { get; set; }
        public bool Prospect { get; set; }
        public System.DateTime DateProspect { get; set; }
        public string CodeRespensableAdministration { get; set; }
        public string Password { get; set; }
        public bool Promo { get; set; }
        public bool Comptoir { get; set; }
        public bool Classic { get; set; }
        public bool ChangerRaisonSociale { get; set; }
        public string CodeDevise { get; set; }
        public string Extention { get; set; }
        public string Login { get; set; }
        public byte[] Logo { get; set; }
        public bool ClientFournisseur { get; set; }
        public string CodeTypeParrain { get; set; }
        public string CodeParrain { get; set; }
        public string CodePays { get; set; }
        public string CodeLangue { get; set; }
        public string CodeSousFamille { get; set; }
        public bool DroitConsommation { get; set; }
        public bool AfficherNbPallete { get; set; }
        public bool BlocagePreavis { get; set; }
        public int NbPreavis { get; set; }
        public bool RemiseQuantite { get; set; }
        public bool RegimeReel { get; set; }
        public decimal Capital { get; set; }
        public bool AutoriserSeuilSuplementaire { get; set; }
        public string DateAutorisationSuplementaire { get; set; }
        public int NbJourSuplementaire { get; set; }
        public decimal ValeurCreditSuplementaire { get; set; }
        public decimal ValeurEngagementSuplementaire { get; set; }
        public bool PrixUsine { get; set; }
        public string CodeVilleLivraison { get; set; }
        public string DateTelevente { get; set; }
        public string DateLivraison { get; set; }
        public string DateRepresentant { get; set; }
        public string DateOuverturePatente { get; set; }
        public int Effectif { get; set; }
        public string CodeFournisseur { get; set; }
        public bool AutreAdresse { get; set; }
        public string NomValidateur { get; set; }
        public string DateValidation { get; set; }
        public decimal SeuilDepassementCredit { get; set; }
        public decimal RecalculSoldeMois { get; set; }
        public decimal DepassementBL { get; set; }
        public bool Agreer { get; set; }
        public bool AnnulerTousControle { get; set; }
        public bool AutoriserFactoring { get; set; }
        public decimal MontantAutorisation { get; set; }
        public byte[] LogoCachet { get; set; }
        public decimal TotaleGarantie { get; set; }
        public bool AvecGaranti { get; set; }
        public byte[] LogoCachet2 { get; set; }
        public System.DateTime DateDerniereModification { get; set; }
        public string DerniereModification { get; set; }
        public string NumeroCarte { get; set; }
        public decimal SoldePoint { get; set; }
        public decimal SoldeValeurPoint { get; set; }
        public bool ActiverDepassementPieceNonPaye { get; set; }
        public string DateAutorisationPieceNonPaye { get; set; }
        public int NBAutorisationPieceNonPaye { get; set; }
        public decimal FraisLogistique { get; set; }
        public string TypeClient { get; set; }
        public string CodeFournisseurAutreBase { get; set; }
        public string NomAutreBase { get; set; }
        public bool VIP { get; set; }
        public bool Terme { get; set; }
        public bool DefalcationBL { get; set; }
        public string CodeClientParent { get; set; }
        public Nullable<bool> Promotion { get; set; }
        public Nullable<decimal> ToleranceVariationQuantiteFabrication { get; set; }
    }
}
