//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CRMSTUBSOFT
{
    using System;
    using System.Collections.Generic;
    
    public partial class ClientCRM
    {
        public string CodeClient { get; set; }
        public string RaisonSociale { get; set; }
        public string Adresse1 { get; set; }
        public string MartriculeFiscale { get; set; }
        public string Tel1 { get; set; }
        public string Email { get; set; }
        public string CodeClientCommercial { get; set; }
        public string MotPasse { get; set; }
        public byte[] imageElement { get; set; }
        public string FileName { get; set; }
        public string imagephysique { get; set; }
    }
}
