//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CRMSTUBSOFT
{
    using System;
    using System.Collections.Generic;
    
    public partial class Crm_PlanningTime
    {
        public int Id_Ligne { get; set; }
        public System.DateTime Date { get; set; }
        public string Titre { get; set; }
        public string Id_Plannig { get; set; }
        public string CodeResponsable { get; set; }
        public string Matin { get; set; }
        public string ApresMidi { get; set; }
        public string CodeClient { get; set; }
        public string RaisonSociale { get; set; }
        public string MatinReel { get; set; }
        public string ApresMidiReel { get; set; }
        public string ObjectisNonRealiser { get; set; }
    
        public virtual Crm_Planning Crm_Planning { get; set; }
    }
}
