//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CRMSTUBSOFT
{
    using System;
    using System.Collections.Generic;
    
    public partial class Crm_HistoriqueType
    {
        public int id { get; set; }
        public string NumeroTache { get; set; }
        public Nullable<int> IdSanction { get; set; }
        public Nullable<int> IdDegres { get; set; }
        public Nullable<System.DateTime> DateOperation { get; set; }
        public string Type { get; set; }
        public string TypePiece { get; set; }
        public string NomValidateur { get; set; }
    }
}
