//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CRMSTUBSOFT
{
    using System;
    using System.Collections.Generic;
    
    public partial class Crm_Planning
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Crm_Planning()
        {
            this.Crm_PlanningTime = new HashSet<Crm_PlanningTime>();
        }
    
        public string Id_Planning { get; set; }
        public Nullable<System.DateTime> Datedebut { get; set; }
        public Nullable<System.DateTime> DateFin { get; set; }
        public string Titre { get; set; }
        public string Description { get; set; }
        public string CodeResponsable { get; set; }
        public string Nom { get; set; }
        public string Prenom { get; set; }
        public string CodeClient { get; set; }
        public string RaisonSocial { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Crm_PlanningTime> Crm_PlanningTime { get; set; }
    }
}
