//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CRMSTUBSOFT
{
    using System;
    using System.Collections.Generic;
    
    public partial class Crm_Notification
    {
        public int NumeroNotification { get; set; }
        public string NomTable { get; set; }
        public string NumeroPiece { get; set; }
        public bool Notifier { get; set; }
        public string Piece { get; set; }
    }
}
