//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CRMSTUBSOFT
{
    using System;
    using System.Collections.Generic;
    
    public partial class Crm_TicketClient
    {
        public string IdTicket { get; set; }
        public string CodeClient { get; set; }
        public string RaisonSociale { get; set; }
        public string Titre { get; set; }
        public System.DateTime DateCreation { get; set; }
        public string Createur { get; set; }
        public string DatePrisEnCharge { get; set; }
        public string PrisEnChargePar { get; set; }
        public System.DateTime DateTicket { get; set; }
    }
}
