//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CRMSTUBSOFT
{
    using System;
    using System.Collections.Generic;
    
    public partial class Crm_Document
    {
        public int Id_Document { get; set; }
        public string Nom { get; set; }
        public string Description { get; set; }
        public string Type { get; set; }
        public string Extension { get; set; }
        public byte[] Data { get; set; }
        public string TypeDocument { get; set; }
        public string Code_Exp { get; set; }
    }
}
