//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CRMSTUBSOFT
{
    using System;
    using System.Collections.Generic;
    
    public partial class Utilisateur
    {
        public string NomUtilisateur { get; set; }
        public string CodeSociete { get; set; }
        public string CodeFonction { get; set; }
        public string Nom { get; set; }
        public string Prenom { get; set; }
        public string MotDePasse { get; set; }
        public string Skin { get; set; }
        public string CodeRepresentant { get; set; }
        public string MotDePasseValidation { get; set; }
        public string MotDePasseAnnulation { get; set; }
        public string MDPValidation { get; set; }
        public string MDPReimpression { get; set; }
        public bool SaisieLibreLivraisonVente { get; set; }
        public bool SaisieLibreReceptionAchat { get; set; }
        public string CodeEmployer { get; set; }
        public bool Admin { get; set; }
        public bool Administrateur { get; set; }
        public string CreerPar { get; set; }
        public string CreerLe { get; set; }
        public bool Actif { get; set; }
        public bool SaisieLibreRetourVente { get; set; }
        public bool SaisieLibreRetourAchat { get; set; }
        public string CodeService { get; set; }
        public string MDPAdministrateur { get; set; }
        public string CodeIntervenant { get; set; }
        public string CodeFonctionAndroid { get; set; }
        public bool SaisieLibreNotification { get; set; }
    
        public virtual Fonction Fonction { get; set; }
    }
}
