//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CRMSTUBSOFT
{
    using System;
    using System.Collections.Generic;
    
    public partial class Crm_CycleExecTache
    {
        public string NumeroTache { get; set; }
        public string Nomutilisateur { get; set; }
        public string OldStatus { get; set; }
        public string NewStatus { get; set; }
        public System.DateTime DateDebutExecution { get; set; }
        public System.DateTime DateFinExecution { get; set; }
        public int Duree { get; set; }
        public int idTacheExec { get; set; }
        public bool Encours { get; set; }
    }
}
