//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CRMSTUBSOFT
{
    using System;
    using System.Collections.Generic;
    
    public partial class Crm_TacheExcution
    {
        public string IdTache { get; set; }
        public string Nomutilisateur { get; set; }
        public string OldEtat { get; set; }
        public string OldStatus { get; set; }
        public string NewEtat { get; set; }
        public string NewStatus { get; set; }
        public System.DateTime DateExcution { get; set; }
        public System.DateTime DateFinExcution { get; set; }
        public int Duree { get; set; }
        public int IdtacheExce { get; set; }
        public string DescriptionAcorriger { get; set; }
        public string DescriptionAValider { get; set; }
        public string DescriptionAExpliquer { get; set; }
    }
}
