//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CRMSTUBSOFT
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.Web.Mvc;

    public partial class Crm_Projet
    {
        public int CodeProjet { get; set; }
        [Required]
        public string CodeTypeProjet { get; set; }
        [Required]
        public string Libelle { get; set; }
        public string MontantProjet { get; set; }
        [Required]
        public Nullable<System.DateTime> DateDeclenchement { get; set; }
        [Required]
        public Nullable<System.DateTime> DateFinPrevu { get; set; }
        public Nullable<bool> Cloture { get; set; }
        public Nullable<System.DateTime> DateCloture { get; set; }
        public string ObjectifProjet { get; set; }
        [AllowHtml]
        public string DescriptionProjet { get; set; }
        [Required(AllowEmptyStrings = true)]
        public string ResponsableProjet { get; set; }
    }
}
