//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CRMSTUBSOFT
{
    using System;
    using System.Collections.Generic;
    
    public partial class PersonnelGRH
    {
        public string MatriculePersonnel { get; set; }
        public string NomPrenom { get; set; }
        public string Lieu { get; set; }
        public string CCB { get; set; }
        public string Adresse { get; set; }
        public string CIN { get; set; }
        public string Nationalite { get; set; }
        public string Sexe { get; set; }
        public string CodeEtatCivil { get; set; }
        public int NB_Enfant { get; set; }
        public string DateEmbauge { get; set; }
        public string DateCNSS { get; set; }
        public bool ChefFamille { get; set; }
        public string CodeOrganigramme { get; set; }
        public string CodeQualification { get; set; }
        public string CodeRegime { get; set; }
        public string CodeCategorie { get; set; }
        public string CodeEchelon { get; set; }
        public decimal CoefConge { get; set; }
        public string CodeNature { get; set; }
        public decimal SalaireBase { get; set; }
        public string CodeTypeContrat { get; set; }
        public string CodeTypeCNSS { get; set; }
        public bool EnActivite { get; set; }
        public bool SoumisImpot { get; set; }
        public bool ParentEnCharge { get; set; }
        public string Observation { get; set; }
        public string CodeModePaiement { get; set; }
        public string CodeBanque { get; set; }
        public string MatriculeAssureSocial { get; set; }
        public string CleAssureSocial { get; set; }
        public string Nom { get; set; }
        public string Prenom { get; set; }
        public string PrenomPere { get; set; }
        public Nullable<int> NbParentACharge { get; set; }
        public string NumCNSS { get; set; }
        public string DateNaissance { get; set; }
        public string DateCIN { get; set; }
        public string DateDebutContrat { get; set; }
        public string DateFinContrat { get; set; }
        public string DateSortie { get; set; }
        public string TypeCNSS2 { get; set; }
        public bool DetailEnfants { get; set; }
        public string Tel { get; set; }
        public string NomConjoint { get; set; }
        public bool ConjointTravail { get; set; }
        public string DateValiditeCHandicape { get; set; }
        public string CodeChargePatronale { get; set; }
        public string NiveauPersonnel { get; set; }
        public string CodeAssurance { get; set; }
        public decimal CotationAssurance { get; set; }
        public string DateAssurance { get; set; }
        public bool AssureChargeSociete { get; set; }
        public string MatriculePersonnelNew { get; set; }
        public byte[] Photo { get; set; }
        public string Session { get; set; }
        public string CodeEmplacement { get; set; }
        public string CodeTypeProductivité { get; set; }
        public string CodeSociete { get; set; }
        public string NomPrenomArabe { get; set; }
        public string AdresseArabe { get; set; }
        public string QualificationArabe { get; set; }
        public decimal anciensalairebasegrille { get; set; }
        public bool RevenuReinvesti { get; set; }
        public string DateReinvesti { get; set; }
        public decimal MontantReinvesti { get; set; }
        public bool FraisPro { get; set; }
        public string NumeroPermis { get; set; }
        public string DateFin { get; set; }
        public string CodeCategoriePermis { get; set; }
        public string ClePermis { get; set; }
        public decimal SalaireNet { get; set; }
        public bool Prospect { get; set; }
        public string TelAutre { get; set; }
        public string TelDomicile { get; set; }
        public string CodeService { get; set; }
        public string CodeSite { get; set; }
        public string NomUtilisateur { get; set; }
        public System.DateTime DateCreation { get; set; }
        public System.DateTime HeureCreation { get; set; }
        public string CodeSupHier { get; set; }
        public bool AppliquerIndemnité { get; set; }
        public decimal ChiffreAffaireEstime { get; set; }
        public decimal MontantAdeduireCAInferieur { get; set; }
        public decimal MontantHeurSuppl { get; set; }
        public bool existedansPointeuse { get; set; }
        public int NbFingerPrint { get; set; }
        public string DateDebutEchelon { get; set; }
        public string DateEchangeEchelon { get; set; }
        public string DateDebutDomSalaire { get; set; }
        public string DateFinDomSalaire { get; set; }
        public bool DemandeDomSalaire { get; set; }
        public string Email { get; set; }
    }
}
