//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CRMSTUBSOFT
{
    using System;
    using System.Collections.Generic;
    
    public partial class Respensable
    {
        public string CodeRespensable { get; set; }
        public string Nom { get; set; }
        public decimal TC1 { get; set; }
        public decimal TC2 { get; set; }
        public decimal TC3 { get; set; }
        public decimal TC4 { get; set; }
        public decimal TC5 { get; set; }
        public decimal TC6 { get; set; }
        public decimal TC7 { get; set; }
        public decimal TP1 { get; set; }
        public decimal TP2 { get; set; }
        public decimal TC8 { get; set; }
        public decimal TP3 { get; set; }
        public decimal TP4 { get; set; }
        public bool Commercial { get; set; }
        public string MatriculePersonnel { get; set; }
        public string CodeService { get; set; }
        public string CodeSuperieurHiearchique { get; set; }
        public bool Actif { get; set; }
        public bool SupHier { get; set; }
    }
}
