//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CRMSTUBSOFT
{
    using System;
    using System.Collections.Generic;
    
    public partial class CompteurPiece
    {
        public string CodeSociete { get; set; }
        public string NomPiecer { get; set; }
        public string PrefixPiece { get; set; }
        public string Annee { get; set; }
        public string Compteur { get; set; }
    }
}
