//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CRMSTUBSOFT
{
    using System;
    using System.Collections.Generic;
    
    public partial class Crm_ModuleNature
    {
        public int IdNatureType { get; set; }
        public string Libelle { get; set; }
        public string Nature { get; set; }
    
        public virtual Crm_TacheNature Crm_TacheNature { get; set; }
    }
}
