//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CRMSTUBSOFT
{
    using System;
    using System.Collections.Generic;
    
    public partial class Crm_Description
    {
        public string IdDescription { get; set; }
        public string TittreTache { get; set; }
        public System.TimeSpan Duree { get; set; }
        public string NumeroPVReunion { get; set; }
    
        public virtual Crm_PVReunion Crm_PVReunion { get; set; }
    }
}
